import { Geist, Geist_Mono, Lora, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Authproviders from "../components/AuthProvider/AuthProvider"; // ✅ new import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const loraFont = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={loraFont.className}>
        <Authproviders>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </Authproviders>
      </body>
    </html>
  );
}
